"""Save discovery picks (artists) to a new Tidal playlist by seeding each
artist's top track(s)."""
from __future__ import annotations

from ...domain.discovery.ports import RecommendationGateway
from ...domain.library.ports import LibraryRepository, MusicGateway, PlaylistWriter


class SaveRecommendationsToPlaylist:
    def __init__(
        self,
        writer: PlaylistWriter,
        rec_gateway: RecommendationGateway,
        music_gateway: MusicGateway,
        repository: LibraryRepository,
    ):
        self._writer = writer
        self._rec = rec_gateway
        self._music = music_gateway
        self._repository = repository

    def __call__(
        self, name: str, artist_ids: list[int], tracks_per_artist: int = 1
    ) -> dict:
        name = (name or "").strip() or "Discoveries"
        playlist_id = self._writer.create_playlist(
            name, "Generated by Tidal Manager — discovery picks"
        )
        track_ids: list[int] = []
        for aid in artist_ids:
            track_ids.extend(self._rec.artist_top_tracks(aid, tracks_per_artist))
        if track_ids:
            self._writer.add_tracks(playlist_id, track_ids)
        # Refresh just this playlist locally.
        self._repository.save_playlist_snapshot(self._music.fetch_playlist(playlist_id))
        return {"playlist_id": playlist_id, "track_count": len(track_ids)}
